baseurl: '/'
permalink: pretty
title: 'Sounds Like Soma'

logo:
  mobile: "images/logo/soma-logo-mobile.webp"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/soma-home-logo.webp"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  blogs:
    output: true
  samples:
    output: true
  reviews:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "samples"
    values:
      layout: "sample"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"

sass:
  style: compressed # possible values: nested expanded compact compressed

url: "https://www.soundslikesoma.com" # the base hostname & protocol for your site

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
