baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Sounds Like Soma'
footer: Sounds Like Soma, LLC

collections:
  services:
    output: true
    permalink: /services/:path/
  blogs:
    output: true
    permalink: /blogs/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  samples:
    output: true
    permalink: /samples/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      type: blogs
    values:
      layout: blog
      bodyClass: page-blogs-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables


url: "https://www.soundslikesoma.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
